# Generated by Django 5.0 on 2026-02-13 22:38

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='emoji',
            field=models.CharField(blank=True, default='🎁', help_text='Emoji del producto (fallback)', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Imagen del producto (jpg/png/webp)', max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
