# Generated by Django 5.0 on 2026-02-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprobante_sinpe_archivo',
            field=models.FileField(blank=True, help_text='Sube imagen o PDF del comprobante SINPE', null=True, upload_to='comprobantes_sinpe/'),
        ),
    ]
